name: CI
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Download Flutter packages
        run: flutter pub get
      - name: Flutter format
        run: flutter format --set-exit-if-changed
      - name: Flutter analyze
        run: flutter analyze --fatal-infos --fatal-warnings
      - name: Flutter test
        run: flutter test